name: wistia_player
version: 0.0.4
description: Flutter package for playing or streaming inline Wistia videos using the official iFrame player API. This plugin supports both Android and iOS.
publish_to: 'none'

environment:
  sdk: ">=2.13.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  webview_flutter: ^4.2.2
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: null
